"""create initial database schema

Revision ID: 598b93a3d62c
Revises: 
Create Date: 2026-09-05 16:32:27.858617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '598b93a3d62c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holder_name', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_tier', sa.Enum('low', 'medium', 'high', name='risk_tier'), nullable=False),
    sa.Column('kyc_level', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_risk_tier', 'accounts', ['risk_tier'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('src_type', sa.String(), nullable=False),
    sa.Column('src_id', sa.Uuid(), nullable=False),
    sa.Column('dst_type', sa.String(), nullable=False),
    sa.Column('dst_id', sa.Uuid(), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_edges_dst', 'entity_edges', ['dst_type', 'dst_id'], unique=False)
    op.create_index('ix_entity_edges_src', 'entity_edges', ['src_type', 'src_id'], unique=False)
    op.create_table('ips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('firstseen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mcc', sa.String(), nullable=False),
    sa.Column('firstseen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sanctions_list',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'pending_review', 'closed', name='case_status'), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('sla_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disposition', sa.Enum('fraud', 'not_fraud', 'sar_filed', name='case_disposition'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('ip_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('channel', sa.Enum('card', 'transfer', 'wallet', name='transaction_channel'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['ip_id'], ['ips.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_account_ts', 'transactions', ['account_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index('ix_transactions_ts_brin', 'transactions', ['ts'], unique=False, postgresql_using='brin')
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('calibrated_prob', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'review', 'decline', name='decision_type'), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_hits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('ix_decisions_decision_ts', 'decisions', ['decision', sa.literal_column('ts DESC')], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('graph', 'timeline', 'typology', 'media', 'note', name='evidence_kind'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Enum('agent', 'human', name='evidence_creator'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ground_truth_labels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('typology', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sar_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('narrative_md', sa.String(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'edited', 'approved', 'rejected', name='sar_status'), nullable=False),
    sa.Column('author', sa.Enum('agent', 'analyst', name='sar_author'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_sar_case_version', 'sar_drafts', ['case_id', 'version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sar_case_version', table_name='sar_drafts')
    op.drop_table('sar_drafts')
    op.drop_table('ground_truth_labels')
    op.drop_table('evidence_items')
    op.drop_index('ix_decisions_decision_ts', table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('alerts')
    op.drop_index('ix_transactions_ts_brin', table_name='transactions', postgresql_using='brin')
    op.drop_index('ix_transactions_account_ts', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('cases')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('sanctions_list')
    op.drop_table('merchants')
    op.drop_table('ips')
    op.drop_index('ix_entity_edges_src', table_name='entity_edges')
    op.drop_index('ix_entity_edges_dst', table_name='entity_edges')
    op.drop_table('entity_edges')
    op.drop_table('devices')
    op.drop_index('ix_accounts_risk_tier', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
